# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WYNullViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for WYNullViewDemo
  pod 'MJRefresh', '~> 3.1.1' 

  target 'WYNullViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WYNullViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
